using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;

namespace Breakout.Levels {

    public class RowParser {

        private List<string> data;

        public RowParser(List<string> data) {
            this.data = data;

        /// <summary>
        /// Uses the string list generated by the provider to generate a data structure containing
        /// the specific level in the form of a string list where each row in the level .txt file
        /// is an element in the list. </summary>
        /// <returns>Returns a list of strings corresponding to the input level rows from the .txt
        /// file</returns>
        }
        public List<string> Parse() {
            if (data.Contains("Map:") && data.Contains("Map/")) {

                var start = data.FindIndex(x => x == "Map:") + 1;
                var end = data.FindIndex(x => x == "Map/");

                return data.GetRange(start, end - start);
            } else {
                throw new InvalidDataException();
            }
        }
    }
}